image:
  repository: registry.gitlab.factory.social.gouv.fr/socialgouv/socialgouv-github-io

nameOverride: www

labels:
  app.kubernetes.io/part-of: www
  owner: www
  team: www

deployment:
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}

  port: 3000

  livenessProbe:
    periodSeconds: 20
    port: 3000
  readinessProbe:
    periodSeconds: 20
    port: 3000

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  env:
    - name: NODE_ENV
      value: "production"

service:
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: "www.fabrique.social.gouv.fr"
      paths:
        - path: /
          servicePort: 3000
  tls:
    - hosts:
        - "www.fabrique.social.gouv.fr"
      secretName: www-crt
