dist: xenial
language: node_js
sudo: false
git:
  depth: 5
node_js: 10
cache: yarn

#

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: Verify
      name: Lint
      script: yarn lint
    - stage: Verify
      name: Build
      script: NODE_ENV=production yarn build
