app:
  ~chart: app # implicit
  ~needs: [build-app]
  containerPort: 8080
  imagePackage: app # implicit
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'none'; connect-src 'self' https://*.gouv.fr; font-src 'self'; img-src 'self'; prefetch-src 'self' https://*.gouv.fr; script-src 'self' https://*.gouv.fr; frame-src 'self' https://*.gouv.fr; style-src 'self' 'unsafe-inline'";
        more_set_headers "X-Frame-Options: deny";
        more_set_headers "X-XSS-Protection: 1; mode=block";
        more_set_headers "X-Content-Type-Options: nosniff";

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          COMMIT_SHA: "{{ $.Values.global.sha }}"
