apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.fabrique.social.gouv.fr$request_uri
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  labels:
    app.kubernetes.io/component: redirect
    app.kubernetes.io/name: www
  name: www-redirect
  namespace: www
spec:
  rules:
    - host: www.incubateur.social.gouv.fr
    - host: incubateur.social.gouv.fr
    - host: fabrique.social.gouv.fr
  tls:
    - hosts:
      - www.incubateur.social.gouv.fr
      - incubateur.social.gouv.fr
      - fabrique.social.gouv.fr
      secretName: www-redirect
