name: Release

on:
  workflow_dispatch:
  push:
    branches: [master, main, alpha, beta, next]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: socialgouv/workflows/actions/semantic-release@v1
        with:
          github-token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
          author-name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          author-email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
