apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: www
  name: job-cleanup
  labels:
    app: www
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: some-container
            image: bash:4.4
            env:
            - name: NAME
              value: world
            command:
              - sh
              - -c
              - echo "Hello $NAME"
          restartPolicy: Never
